id: P006819
initial_creation_type: ocr
source_metadata:
  id: bdr:W1KG25171
  title: བསླབ་བྱ་ནོར་བུའི་གླིང་དུ་བགྲོད་པའི་ལམ་ཡིག་སོགས་བསླབ་བྱ་སྣ་ཚོགས།
  author: ''
  volumes:
    bdcf33092b1740b096796b02d2e6d486:
      image_group_id: I1KG25173
      title: ''
      volume_number: 1
      total_pages: 107
      base_file: v001.txt
